config/routes.rb
Rails.application.routes.draw do

  #static pages
  get 'home/index'
  get 'photos/feature_example'
  
  root :to => "photos#index"

  devise_for :users, controllers: { registrations: "registrations"}
  
  resources :profiles, except: :destroy do 
    resources :photos, controller: 'profiles/photos', only: [:index,:show,:new,:create]
  end

  resources :photos, except: [:edit, :update] do 
    resources :critiques, controller: 'photos/critiques'
  end
  
end

app/models/critique.rb
class Critique < ActiveRecord::Base

  belongs_to :photo
  belongs_to :profile
  
end

app/models/photo.rb
class Photo < ActiveRecord::Base

  belongs_to :profile
  has_many :critiques
  has_many :profiles, through: :critiques
  validates_presence_of :title, :status

  mount_uploader :photo_upload, PhotoUploadUploader

  def been_reviewed?(profile)
    critique = critiques.where(profile_id: profile).first
    critique.nil?
  end

  
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  
  belongs_to :user
  has_many :photos

  has_many :critiques
  has_many :photos, through: :critiques

  validates_presence_of :first_name, :last_name, :location, :country


  def country_name
    country_name = ISO3166::Country[country]
    country_name.translations[I18n.locale.to_s] || country.name
  end

  def full_name
    "#{first_name} #{last_name}"
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :email, :encrypted_password

  has_one :profile

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper :all

  def configure_permitted_parameters
   devise_parameter_sanitizer.for(:sign_up) << :username
  end

  



end

app/controllers/home_controller.rb
class HomeController < ApplicationController


  before_action :authenticate_user!
  layout 'user'

  def index

  end


end

app/controllers/photos/critiques_controller.rb
class Photos::CritiquesController < ApplicationController 

  before_action :authenticate_user!

  def new 
    @photo = Photo.find(params[:photo_id])
    @critique = Critique.new
  end

  def create 
    @photo = Photo.find(params[:photo_id])
    @profile = current_user.profile
    @critique = Critique.new(critique_params)
    @critique.photo_id = @photo.id
    @critique.profile_id = @profile.id
    if @critique.save
      redirect_to photo_path(@photo)
    else
      redirect_to root_path
    end
  end

  def view_critiques
    @photo = Photo.find(params[:photo_id])
    @critique = Critique.find(params[:id])
    render :partial=> 'view_critique'  
  end
  helper_method :view_critique

  
  private

  def critique_params
    params.require(:critique).permit(:first_impressions, :composition, :lighting)
  end


end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController 
  
  before_action :authenticate_user!, except: [:index, :feature_example]
  before_action :photo_been_reviewed_by_user?, only: [:show]

  layout 'user'

  def index
    @photos = Photo.all
  end

  def new 
    @photo = Photo.new
  end

  def create
    @photo = Photo.new(photos_params)
    @photo.profile_id = current_user.profile

    if @photo.save
      redirect_to @photo
    else
      render :new
    end
  end

  def show
    @photo = Photo.find(params[:id])
  end

  def feature_example
  end

  private 

  def photo_been_reviewed_by_user?
    @photo = Photo.find(params[:id])
    @profile = current_user.profile
    @been_reviewed = @photo.been_reviewed?(@profile.id)
  end

  def photos_params
    params.require(:photo).permit(:title, :photo_upload, :description, :status)
  end
  
end

app/controllers/profiles/photos_controller.rb
class Profiles::PhotosController < ApplicationController

  before_action :authenticate_user!
  layout 'user'

  def index 
  end

  def show 
    @profile = Profile.find(params[:profile_id])
    @photo = Photo.find(params[:id])
  end

  private 

  def photos_params
    params.require(:photo).permit(:title, :description, :photo_upload, :status)
  end


end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  respond_to :html, :js

  before_action :authenticate_user!
  layout 'user', except: [:new]
 
  def new
    @profile = Profile.new
  end

  def show
    @profile = Profile.find(params[:id])
  end

  def create
    @profile = Profile.new(profile_params)
    @profile.user_id = current_user.id
    if @profile.save
      redirect_to @profile
    else
      render :new
    end
  end

  def edit
    @profile = Profile.find(params[:id])
  end

  def update 
    @profile = Profile.find(params[:id])
    if @profile.update_attributes(profile_params)
      redirect_to @profile
    else
      render :edit 
    end
  end



  private

  def profile_params
    params.require(:profile).permit(:first_name, :last_name, :location, :country, :about_me, :user_id)
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  
  protected

  def after_sign_up_path_for(resource)
    new_profile_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.haml
%h1 Welcome! You have signed up successfully.

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no", :name => "viewport"}/
    %title 600px - Take your skills to the next level
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    %link{:href => "https://fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,400italic,500,500italic,700,700italic,900", :rel => "stylesheet", :type => "text/css"}


  %body
    = yield

app/views/layouts/user.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no", :name => "viewport"}/
    %title 600px - Take your skills to the next level
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    %link{:href => "https://fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,400italic,500,500italic,700,700italic,900", :rel => "stylesheet", :type => "text/css"}

  .navigation_wrapper
    .container.navigation.clearfix
      .wrapper
        %h3.brand-logo
          600px
        %ul.navigation-item.pull-left
          %li
            = link_to root_path do  
              %i.fa.fa-home.fa-1x  
              Home     
          %li
            = link_to root_path do
              %i.fa.fa-picture-o.fa-1x.span 
              Discover
          %li
            = link_to root_path do
              %i.fa.fa-comments.fa-1x 
              Groups
        %ul.profile-item.pull-right
          %li.dropdown
            - if user_signed_in?
              %button#dropdownMenu1.btn.btn-profile.dropdown-toggle.user-name{"aria-expanded" => "true", "aria-haspopup" => "true", "data-toggle" => "dropdown", :type => "button"}
                = current_user.profile.first_name 
                = current_user.profile.last_name
                %span.caret
              %ul.dropdown-menu{"aria-labelledby" => "dropdownMenu1"}
                %li
                  = link_to 'view profile', profile_path(current_user)
                %li
                  = link_to 'log out', destroy_user_session_path, method: :delete
            - else
              %li.user-sign-in
                = link_to new_user_session_path do
                  %i.fa.fa-sign-in.fa-1x 
                  Sign In
              

          %li
            = link_to new_photo_path, class: 'upload-photo' do 
              .btn.btn-upload{style: 'border-radius: 0px;'}
                %i.fa.fa-upload.fa-1x.upload-item 
                  Upload
              
  .navigation-mobile-wrapper
    %nav.navbar.navbar-inverse{:role => "navigation"}
      .navbar-header
        %button.navbar-toggle{"data-target" => "#navbarCollapse", "data-toggle" => "collapse", :type => "button"}
          %span.sr-only Toggle navigation
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand{:href => '/photos'} 600px
      #navbarCollapse.collapse.navbar-collapse
        %ul.nav.navbar-nav
          - if user_signed_in?
            %li.link_nav_menu
              = link_to 'profile', profile_path(current_user)
            %li.link_nav_menu
              = link_to 'Log out', destroy_user_session_path, method: :delete
          %li.link_nav_menu
            = link_to 'Upload new photo', new_photo_path
          
          
            


  %body
    = yield

app/views/photos/_form.html.haml
= simple_form_for [@profile,@photo] do |f|
  = f.input :title
  = f.input :status
  = f.input :photo_upload
  = f.input :description
  = f.button :submit

app/views/photos/critiques/_form.html.haml
= simple_form_for [@photo,Critique.new] do |f|
  = f.input :first_impressions, :input_html => {:rows => 5, style: 'max-width: 100%; height: 100%;'}
  = f.input :composition, :input_html => {:rows => 3, style: 'max-width: 100%; height: 100%;'}
  = f.input :lighting, :input_html => {:rows => 3, style: 'max-width: 100%; height: 100%;'}
  = f.button :submit

app/views/photos/critiques/new.html.haml
= render 'form'

app/views/photos/feature_example.html.haml
#content
  .main-container
    
    .photo-container.pull-left
      = image_tag('stars.jpg', class: 'resp-img')
    .photo-sidebar.pull-right
      %p.photo-review 
        Review by
      .profile-info-wrapper
        .profile-info
          .profile-photo
            = image_tag('default-user.png', class: 'user-photo')
          .profile-full-name
            %p Philippe AKA

      .new-critique
        .new-critique-details
          %h4
            %i.fa.fa-eye.fa-1x 
              First Impressions
          %p
            Lorem ipsum dolor sit amet, vel brute soluta petentium ex. Putent detracto ne cum, in pro putent feugait. Quo eu mutat tritani tractatos.

        .new-critique-details
          %h4
            %i.fa.fa-file-image-o.fa-1x 
              Composition
          %p
            Lorem ipsum dolor sit amet, vel brute soluta petentium ex. Putent detracto ne cum, in pro putent feugait. Quo eu mutat tritani tractatos. 

        .new-critique-details
          %h4
            %i.fa.fa-bolt.fa-1x 
              Lighting
          %p
            Lorem ipsum dolor sit amet, vel brute soluta petentium ex. Putent detracto ne cum, in pro putent feugait. Quo eu mutat tritani tractatos. 

    .photo-review-mobile
      %p.photo-review 
        Review by
        .profile-info-wrapper
          .profile-info
            .profile-photo
              = image_tag('default-user.png', class: 'user-photo')
            .profile-full-name
              %p Philippe AKA

        .new-critique
          .new-critique-details.col-md-4
            %h4
              %i.fa.fa-eye.fa-1x 
                First Impressions
            %p
              Lorem ipsum dolor sit amet, vel brute soluta petentium ex. Putent detracto ne cum, in pro putent feugait. Quo eu mutat tritani tractatos.

          .new-critique-details.col-md-4
            %h4
              %i.fa.fa-file-image-o.fa-1x 
                Composition
            %p
              Lorem ipsum dolor sit amet, vel brute soluta petentium ex. Putent detracto ne cum, in pro putent feugait. Quo eu mutat tritani tractatos. 

          .new-critique-details.col-md-4
            %h4
              %i.fa.fa-bolt.fa-1x 
                Lighting
            %p
              Lorem ipsum dolor sit amet, vel brute soluta petentium ex. Putent detracto ne cum, in pro putent feugait. Quo eu mutat tritani tractatos. 
      



      

app/views/photos/index.html.haml
.background-header
  .container
    .row
      .col-xs-12
        .subheader
          %ul
            %li Flow
            %li Following
            %li Activity

.container
  .row
    .col-xs-12      
      .new-feature-wrapper
        .new-feature
          %h3.title-feature
            Looking to improve your photography skills ? 

          %p.feature-details
            Submit your shots to 600px with the tag 600pxbestadvice and you could have the chance to win a full review of your work by our team!

          .example-feature
            = link_to 'view example', photos_feature_example_path, class: 'btn btn-feature'



      .wrapper-photos-index
        %ul
          - @photos.each do |photo|
            %li.photo-wrapper
              = link_to photo_path(photo.id) do 
                = image_tag(photo.photo_upload, class: 'resp-img')
  

      
        
      

app/views/photos/new.html.haml
.container
  .row
    .col-xs-12
      %h2 upload a new photo #{current_user.profile.first_name}!
      = render 'form'

app/views/photos/show.html.haml
#content
  .main-container
    .photo-container.pull-left
      = image_tag(@photo.photo_upload.url, class: 'resp-img')
    .photo-sidebar.pull-right
      %p.photo-review 
        Review by
      .profile-info-wrapper
        .profile-info
          .profile-photo
            = image_tag('default-user.png', class: 'user-photo')
          .profile-full-name
            = current_user.profile.full_name

      .new-critique
        - if @been_reviewed  
          .critique-details
            = render 'photos/critiques/form'
        - else 
          .new-critique-details
            %h4
              %i.fa.fa-eye.fa-1x 
                First Impressions
            %p
              = @photo.critiques.last.first_impressions

          .new-critique-details
            %h4
              %i.fa.fa-file-image-o.fa-1x 
                Composition
            %p
              = @photo.critiques.last.composition

          .new-critique-details
            %h4
              %i.fa.fa-bolt.fa-1x 
                Lighting
            %p
              = @photo.critiques.last.lighting

    .photo-review-mobile
      %p.photo-review 
        Review by
        .profile-info-wrapper
          .profile-info
            .profile-photo
              = image_tag('default-user.png', class: 'user-photo')
            .profile-full-name
              %p Philippe AKA

        .new-critique-mobile
          - if @been_reviewed  
            .critique-details
              = render 'photos/critiques/form'
          - else 
            .new-critique-details.col-md-4
              %h4
                %i.fa.fa-eye.fa-1x 
                  First Impressions
              %p
                = @photo.critiques.last.first_impressions

            .new-critique-details.col-md-4
              %h4
                %i.fa.fa-file-image-o.fa-1x 
                  Composition
              %p
                = @photo.critiques.last.composition

            .new-critique-details.col-md-4
              %h4
                %i.fa.fa-bolt.fa-1x 
                  Lighting
              %p
                = @photo.critiques.last.lighting



  

app/views/profiles/_form.html.haml
= simple_form_for @profile do |f|
  = f.input :first_name 
  = f.input :last_name
  = f.input :location 
  = f.input :country, as: :country
  = f.input :about_me
  = f.button :submit

app/views/profiles/edit.html.haml
.container
  .row
    .col-xs-12.col-md-5.col-centered
      = render 'form'

app/views/profiles/new.html.haml
#profile-wrapper
  .container
    .row
      .col-xs-12.col-md-5.col-centered
        .profile-title
          %h4 
            Thank you for joinning the photography community!
            %p 
              Create your profile and upload your first photo
        .profile-new-form
          = render 'form'

app/views/profiles/photos/new.html.haml
%h2 upload a new photo #{current_user.profile.first_name}!

= simple_form_for [@profile,@photo] do |f|
  = f.input :title
  = f.input :status
  = f.input :photo_upload
  = f.input :description
  = f.button :submit

app/views/profiles/photos/show.html.haml
#content
  .main-container
    .photo-container.pull-left
      = image_tag(@photo.photo_upload.url, class: 'resp-img')
    .photo-sidebar.pull-right
      .profile-info-wrapper
        .profile-info
          .profile-photo.pull-left
            = image_tag('default-user.png', class: 'user-photo')
          .profile-full-name
            = current_user.profile.full_name

app/views/profiles/show.html.haml
.container-fluid
  .row
    .col-xs-12
      .profile-header
        .cover-photo
          .cover-wrap
            .image
        .profile-image
          .avatar-wrapper
            .avatar
              = image_tag('default-user.png', class: 'image-profile')
        .profile-buttons
          .wrapper
            = link_to 'Complete Your Profile', edit_profile_path(@profile), class: 'btn btn-default'

        .profile-info
          %ul.list-unstyled
            %li
              = @profile.first_name
            %li
              = @profile.last_name
            %li
              = @profile.location